#!/bin/bash
clear

if ! yt-dlp --version &>/dev/null;then
	echo "Install yt-dlp first."
	exit 1
fi

version="v1.1.0"
set -o pipefail

out="--restrict-filenames -o %(title)s.%(ext)s"
dlp="yt-dlp -i"
red="\033[1;31m"
sea="\033[1;36m"
ice="\033[1;37m"
end="\033[0;00m"

banner() {
	echo -en $sea
	echo -n '
 __ __   ___     ___   ____     ___
 || ||  // \\   // \\  || \\   // \\
 \\ // ((   )) ((   )) ||  )) ((   ))
  \V/   \\_//   \\_//  ||_//   \\_//

'
	echo -e "$ice       \"VIDEO AUDIO DOWNLOAD\""
	echo -e "$red      -======================-"
	echo -e "$ice            {${sea}entity015♥${ice}}     "
	echo -e "
"
}

read -d '' help 0<<++

Usage:
  $0 <options>
  $0 -f mp4 -s 1080 -u <url> -r 1-2,5
  $0 -f mp3 -i favs.txt

Options:
  -u	Input URL
  -i	Input file
  -f	Format mp3,mp4,subtitle (default:mkv)
  -s	Video resolution 480,720 (default:highest)
  -r	Playlist range 1,2-6
  -h	Print this help
  -v	Print version

$version
++

banner

if [[ ! $1 ]];then
	echo "$help"
	exit 1
fi

fmt="mkv"
res="8192"
lan="en"
while [[ -n "$1" ]];do
	if [[ $1 =~ ^- && ! $1 == "--" ]];then
		case $1 in
		-h | --help )
			echo "$help"
			exit 0
			;;
		-v | --version )
			echo "$version"
			exit 0
			;;
		-u | --url )
			shift
			url=$1
			;;
		-f | --format )
			shift
			fmt=$1
			;;
		-s | --size )
			shift
			res=$1
			;;
		-r | --range )
			shift
			ran="${1/*/--yes-playlist --playlist-items $1}"
			;;
		-l | --language )
			shift
			lan=$1
			;;
		-i | --input-file )
			shift
			file="${1/*/-a $1}"
			;;
		esac
	fi
	shift
done

if [[ ! $file && ! $url ]];then
	echo "No URL/File specified."
	exit 1
fi

declare -A formats

formats[mkv]="-f bv*[height<=$res]+ba/b[height<=$res] --merge-output-format mkv"
formats[mp4]="-f bv*[ext=mp4][height<=$res]+ba[ext=m4a]/b[ext=mp4][height<=$res] --merge-output-format mp4"
formats[mp3]="-f ba -x --audio-format mp3"
formats[subtitle]="--write-subs --sub-langs $lan --skip-download"

format="${formats[$fmt]}"

if [[ $fmt == "subtitle" || $fmt == "mp3" ]];then
	$dlp $format $out $ran $url $file
	exit 0
fi

$dlp $format --embed-subs $out $ran $url $file
